name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.token }}
          plugin_languages: yes
          plugin_languages_ignored: "CSS,SCSS,SASS" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          plugin_followup: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          plugin_lines: yes  
